---
- hosts: jiraview
  user: root
  tasks:
    # This should possibly be a module that just check whether python 2.7 is there before doing anything
    - name: Download Python27 source
      get_url: url=http://python.org/ftp/python/2.7.4/Python-2.7.4.tgz dest=/tmp/Python-2.7.4.tgz owner=root group=root force=no
    - name: Extract Python27 source
      command: /bin/tar -xzf /tmp/Python-2.7.4.tgz chdir=/usr/local/src creates=/usr/local/src/Python-2.7.4/configure
    - name: Make and *ALT* install Python27
      shell: ./configure --prefix=/usr/local && /usr/bin/make && /usr/bin/make altinstall chdir=/usr/local/src/Python-2.7.4/ creates=/usr/local/bin/python2.7
    - name: easy_install
      yum: name=python-setuptools state=installed
    - name: pip + virtualenv
      easy_install: name=$item
      with_items:
        - pip
        - virtualenv
